service: serverless-http-api-dynamodb
frameworkVersion: '4'
configValidationMode: error

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['@aws-sdk/*']
    target: 'node22'
    format: 'esm'

provider:
  name: aws
  region: us-west-2
  runtime: nodejs22.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: functions/create.create
    events:
      - httpApi:
          path: /todos
          method: post

  list:
    handler: functions/list.list
    events:
      - httpApi:
          path: /todos
          method: get

  get:
    handler: functions/get.get
    events:
      - httpApi:
          path: /todos/{id}
          method: get

  update:
    handler: functions/update.update
    events:
      - httpApi:
          path: /todos/{id}
          method: put

  delete:
    handler: functions/delete.deleteHandler
    events:
      - httpApi:
          path: /todos/{id}
          method: delete

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
